package confluence

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"sync"
)

// Client publishes pages to one Confluence Cloud space through the v2 REST
// API. BaseURL is the site root, e.g. https://example.atlassian.net.
type Client struct {
	BaseURL      string
	Email        string
	Token        string
	SpaceKey     string
	ParentPageID string
	HTTPClient   *http.Client

	mu      sync.Mutex
	spaceID string
}

type pageBody struct {
	Representation string `json:"representation"`
	Value          string `json:"value"`
}

type pageVersion struct {
	Number  int    `json:"number"`
	Message string `json:"message,omitempty"`
}

type pageRequest struct {
	ID       string       `json:"id,omitempty"`
	SpaceID  string       `json:"spaceId,omitempty"`
	ParentID string       `json:"parentId,omitempty"`
	Status   string       `json:"status"`
	Title    string       `json:"title"`
	Body     pageBody     `json:"body"`
	Version  *pageVersion `json:"version,omitempty"`
}

type pageResponse struct {
	ID   string `json:"id"`
	Body struct {
		Storage pageBody `json:"storage"`
	} `json:"body"`
	Version struct {
		Number int `json:"number"`
	} `json:"version"`
	Links struct {
		WebUI string `json:"webui"`
		Base  string `json:"base"`
	} `json:"_links"`
}

// PublishPage writes markdown as the page titled title, updating the page
// when one with that title already exists in the space, and returns the
// page's web URL.
func (c *Client) PublishPage(ctx context.Context, title, markdown string) (string, error) {
	spaceID, err := c.lookupSpaceID(ctx)
	if err != nil {
		return "", err
	}
	existing, found, err := c.findPage(ctx, spaceID, title, false)
	if err != nil {
		return "", err
	}

	page := pageRequest{
		Status: "current",
		Title:  title,
		Body:   pageBody{Representation: "storage", Value: MarkdownToStorage(markdown)},
	}
	var published pageResponse
	if found {
		page.ID = existing.ID
		page.Version = &pageVersion{Number: existing.Version.Number + 1, Message: "Regenerated by Jira AI Agent"}
		err = c.sendJSON(ctx, http.MethodPut, "/wiki/api/v2/pages/"+url.PathEscape(existing.ID), "PUT page", page, &published)
	} else {
		page.SpaceID = spaceID
		page.ParentID = strings.TrimSpace(c.ParentPageID)
		err = c.sendJSON(ctx, http.MethodPost, "/wiki/api/v2/pages", "POST page", page, &published)
	}
	if err != nil {
		return "", err
	}
	return c.webURL(published)
}

// PageContent returns the storage-format body of the page titled title, and
// whether such a page exists in the space.
func (c *Client) PageContent(ctx context.Context, title string) (string, bool, error) {
	spaceID, err := c.lookupSpaceID(ctx)
	if err != nil {
		return "", false, err
	}
	page, found, err := c.findPage(ctx, spaceID, title, true)
	if err != nil || !found {
		return "", false, err
	}
	return page.Body.Storage.Value, true, nil
}

func (c *Client) lookupSpaceID(ctx context.Context) (string, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.spaceID != "" {
		return c.spaceID, nil
	}

	var payload struct {
		Results []struct {
			ID string `json:"id"`
		} `json:"results"`
	}
	query := url.Values{"keys": {c.SpaceKey}}
	if err := c.sendJSON(ctx, http.MethodGet, "/wiki/api/v2/spaces?"+query.Encode(), "GET space", nil, &payload); err != nil {
		return "", err
	}
	if len(payload.Results) == 0 {
		return "", fmt.Errorf("Confluence space %q not found", c.SpaceKey)
	}
	c.spaceID = payload.Results[0].ID
	return c.spaceID, nil
}

func (c *Client) findPage(ctx context.Context, spaceID, title string, withBody bool) (pageResponse, bool, error) {
	var payload struct {
		Results []pageResponse `json:"results"`
	}
	query := url.Values{"space-id": {spaceID}, "title": {title}, "status": {"current"}}
	if withBody {
		query.Set("body-format", "storage")
	}
	if err := c.sendJSON(ctx, http.MethodGet, "/wiki/api/v2/pages?"+query.Encode(), "GET pages", nil, &payload); err != nil {
		return pageResponse{}, false, err
	}
	if len(payload.Results) == 0 {
		return pageResponse{}, false, nil
	}
	return payload.Results[0], true, nil
}

func (c *Client) webURL(page pageResponse) (string, error) {
	if page.Links.WebUI == "" {
		return "", fmt.Errorf("Confluence response has no page link")
	}
	base := strings.TrimRight(page.Links.Base, "/")
	if base == "" {
		base = strings.TrimRight(c.BaseURL, "/") + "/wiki"
	}
	return base + page.Links.WebUI, nil
}

// sendJSON encodes request (when non-nil) as the body and decodes the
// response into response. Errors never include the response body.
func (c *Client) sendJSON(ctx context.Context, method, path, operation string, request, response any) error {
	var body io.Reader
	if request != nil {
		encoded, err := json.Marshal(request)
		if err != nil {
			return fmt.Errorf("%s: encode request: %w", operation, err)
		}
		body = bytes.NewReader(encoded)
	}
	httpRequest, err := http.NewRequestWithContext(ctx, method, strings.TrimRight(c.BaseURL, "/")+path, body)
	if err != nil {
		return fmt.Errorf("%s: %w", operation, err)
	}
	httpRequest.SetBasicAuth(c.Email, c.Token)
	httpRequest.Header.Set("Accept", "application/json")
	if request != nil {
		httpRequest.Header.Set("Content-Type", "application/json")
	}

	httpClient := c.HTTPClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	httpResponse, err := httpClient.Do(httpRequest)
	if err != nil {
		return fmt.Errorf("%s: %w", operation, err)
	}
	defer httpResponse.Body.Close()
	if httpResponse.StatusCode < http.StatusOK || httpResponse.StatusCode >= http.StatusMultipleChoices {
		return fmt.Errorf("%s: Confluence returned HTTP %d", operation, httpResponse.StatusCode)
	}
	if err := json.NewDecoder(httpResponse.Body).Decode(response); err != nil {
		return fmt.Errorf("%s: decode response: %w", operation, err)
	}
	return nil
}
